fun_facts = {
    "quirk" : "Everyone has a quirk—it's what makes people unique.",
    "orbit" : "The Moon takes about 27.3 days to orbit Earth.",
    "shard" : "Ancient archaeologists learn a lot from tiny pottery shards.",
    "gnome" : "Garden gnomes became popular in Europe over 150 years ago.",
    "igloo" : "Igloos are excellent insulators, keeping the inside surprisingly warm.",
    "lemon" : "Lemons can conduct electricity because they contain citric acid.",
    "comet" : "Some comets have tails millions of miles long.",
    "cocoa" : "Chocolate comes from cocoa beans that grow in tropical regions.",
    "macaw" : "Macaws can live for over 50 years.",
    "funky" : "The word 'funky' originally referred to a strong smell.",
    "jumbo" : "'Jumbo' became popular after a famous circus elephant named Jumbo.",
    "slate" : "Slate is a rock often used for roofing and chalkboards.",
    "pique" : "'Pique your interest' means to spark curiosity.",
    "okapi" : "Okapis are the closest living relatives of giraffes.",
    "sauce" : "The oldest known sauces date back thousands of years.",
    "cramp" : "Stretching often helps relieve muscle cramps.",
    "brake" : "Disc brakes are commonly used in modern cars and bicycles.",
    "quick" : "A cheetah is the quickest land animal.",
    "crazy" : "Octopuses have some surprisingly crazy problem solving skills.",
    "dozen" : "A dozen always means exactly 12.",
    "enjoy" : "Laughing helps your brain release feel good chemicals.",
    "heavy" : "Neutron stars are among the heaviest objects in the universe.",
    "lucky" : "Four leaf clovers are estimated to occur once in every 5,000 clovers.",
    "shock" : "Lightning can heat the air to five times hotter than the Sun's surface.",
    "thick" : "The thickest tree in the world is over 30 feet wide.",
    "quiet" : "The quietest room ever built is so silent you can hear your heartbeat.",
    "major" : "Jupiter is the major planet in our solar system by size.",
    "equal" : "The equal sign (=) was invented in 1557.",
    "judge" : "In many sports, judges score performances instead of measuring time.",
    "exact" : "Computers can perform calculations with exact precision.",
    "juice" : "Orange juice is one of the world's most popular breakfast drinks.",
    "quote" : "Famous quotes can be remembered for hundreds of years.",
    "chief" : "A chief is often the leader of a group or community.",
    "index" : "Most books have an index to help readers find topics quickly.",
    "watch" : "The first wristwatches became popular over 100 years ago.",
    "block" : "LEGO blocks are made with incredible precision.",
    "weigh" : "Astronauts weigh less on the Moon because gravity is weaker.",
    "pitch" : "A baseball pitch can travel over 100 mph.",
    "beach" : "Some beaches have black, pink, or even green sand.",
    "works" : "The human brain works even while you sleep.",
    "think" : "Humans have thousands of thoughts every day.",
    "argue" : "Healthy arguments can help people solve problems.",
    "album" : "The world's best selling album is *Thrillerby Michael Jackson.",
    "actor" : "Some actors spend months learning new skills for a role.",
    "daily" : "Drinking enough water daily helps your body function well.",
    "doubt" : "Scientists use doubt to test ideas before accepting them.",
    "earth" : "Earth is the only known planet with life.",
    "fruit" : "Bananas are technically berries, but strawberries aren't.",
    "fiber" : "Fiber helps keep your digestive system healthy.",
    "giant" : "Giant sequoias are among the largest trees on Earth.",
    "ghost" : "There is no scientific evidence that ghosts exist.",
    "horse" : "Horses can sleep standing up.",
    "humor" : "Laughing is a universal form of humor across cultures.",
    "index" : "Search engines use huge indexes to find websites quickly.",
    "image" : "The first digital image was created in 1957.",
    "imply" : "To imply means to suggest something without saying it directly.",
    "joint" : "Your body has over 300 joints at birth.",
    "knife" : "The sharpest knives are often made from high carbon steel.",
    "knead" : "Kneading bread helps develop the dough's gluten.",
    "laugh" : "Laughing can strengthen your immune system.",
    "moral" : "Many fairy tales end with a moral or lesson.",
    "noise" : "Sound cannot travel through outer space because there is no air.",
    "night" : "The darkest nights are best for seeing stars.",
    "newly" : "Newly hatched sea turtles instinctively head toward the ocean.",
    "ought" : "'Ought' is one of the oldest words in English.",
    "ocean" : "Over 80% of the ocean remains unexplored.",
    "owner" : "Dogs often recognize their owner's voice instantly.",
    "piano" : "A standard piano has 88 keys.",
    "route" : "GPS systems calculate the fastest route in seconds.",
    "ratio" : "Ratios are used in everything from recipes to maps.",
    "relax" : "Deep breathing helps your body relax.",
    "twice" : "Hummingbirds can flap their wings over 50 times per second.",
    "truck" : "The world's largest trucks are taller than many houses.",
    "uncle" : "The word 'uncle' exists in almost every language.",
    "under" : "Some caves extend hundreds of feet under the ground.",
    "urban" : "More than half of the world's population lives in urban areas.",
    "video" : "The first YouTube video was uploaded in 2005.",
    "vital" : "Water is vital for all known forms of life.",
    "viras" : "'Viras' is a rare name and not a common English word.",
    "whole" : "A whole pizza can be divided into many equal slices.",
    "watch" : "The most expensive watch ever sold cost over $30 million.",
    "yield" : "Some fruit trees yield hundreds of fruits in a single season.",
    "youth" : "Your brain continues developing through your youth and into your 20s.",
    "young" : "Young elephants suck their trunks like babies suck their thumbs.",
    "zilch" : "'Zilch' is a slang word meaning zero or nothing.",
    "zebra" : "Every zebra has a unique stripe pattern.",
    "crane" : "A construction crane can lift hundreds of tons.",
    "jokes" : "Laughing at jokes releases endorphins, which improve your mood."
}
